// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb-wxFENC6qA3HKi-r_RGUFo31iXh35VE',
    appId: '1:304208532585:web:dea082091d721996753ef8',
    messagingSenderId: '304208532585',
    projectId: 'fir-1-6a7fa',
    authDomain: 'fir-1-6a7fa.firebaseapp.com',
    storageBucket: 'fir-1-6a7fa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFDplXpY05QLXMfxMijZKrP7d3zOhJ2iw',
    appId: '1:304208532585:android:56da69b5d30b7458753ef8',
    messagingSenderId: '304208532585',
    projectId: 'fir-1-6a7fa',
    storageBucket: 'fir-1-6a7fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZTfZWRKEbZxap2kNRCnzQQOJ50RcADVw',
    appId: '1:304208532585:ios:021d6efa1483522c753ef8',
    messagingSenderId: '304208532585',
    projectId: 'fir-1-6a7fa',
    storageBucket: 'fir-1-6a7fa.appspot.com',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZTfZWRKEbZxap2kNRCnzQQOJ50RcADVw',
    appId: '1:304208532585:ios:021d6efa1483522c753ef8',
    messagingSenderId: '304208532585',
    projectId: 'fir-1-6a7fa',
    storageBucket: 'fir-1-6a7fa.appspot.com',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb-wxFENC6qA3HKi-r_RGUFo31iXh35VE',
    appId: '1:304208532585:web:7017e61912d29846753ef8',
    messagingSenderId: '304208532585',
    projectId: 'fir-1-6a7fa',
    authDomain: 'fir-1-6a7fa.firebaseapp.com',
    storageBucket: 'fir-1-6a7fa.appspot.com',
  );
}
