// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACjqhffqbcBFlLOGm37IH2gaT9ejAFv0o',
    appId: '1:600621846937:web:4db0247bc94087589a0308',
    messagingSenderId: '600621846937',
    projectId: 'classapp1-35883',
    authDomain: 'classapp1-35883.firebaseapp.com',
    storageBucket: 'classapp1-35883.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO2RczvlETaOfOhUM562va05s8ZvBYvGA',
    appId: '1:600621846937:android:d35478219a69ab569a0308',
    messagingSenderId: '600621846937',
    projectId: 'classapp1-35883',
    storageBucket: 'classapp1-35883.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_EAluFwk3AWoYVn1Uo4CEnLomN-iBbO0',
    appId: '1:600621846937:ios:3ef5df0bb711a6079a0308',
    messagingSenderId: '600621846937',
    projectId: 'classapp1-35883',
    storageBucket: 'classapp1-35883.appspot.com',
    iosBundleId: 'com.example.classapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_EAluFwk3AWoYVn1Uo4CEnLomN-iBbO0',
    appId: '1:600621846937:ios:3ef5df0bb711a6079a0308',
    messagingSenderId: '600621846937',
    projectId: 'classapp1-35883',
    storageBucket: 'classapp1-35883.appspot.com',
    iosBundleId: 'com.example.classapp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACjqhffqbcBFlLOGm37IH2gaT9ejAFv0o',
    appId: '1:600621846937:web:f1a3f8739954f2429a0308',
    messagingSenderId: '600621846937',
    projectId: 'classapp1-35883',
    authDomain: 'classapp1-35883.firebaseapp.com',
    storageBucket: 'classapp1-35883.appspot.com',
  );
}
